baseURL = "https://iyeraravind.github.io/typo"
languageCode = "en-us"
theme = "typo"
MetaDataFormat = "toml"
title = "Typo Theme"
pygmentsStyle = "friendly"
pygmentsCodefences = "true"
pygmentsOptions = ["linenos=table"]
publishDir = "docs"

[params]
  AuthorName = "Aravind Iyer"
  GitHubUser = "iyeraravind"
  Description = "A theme that mostly aims to get out of the way!"
  Title = "Typo"

[permalinks]
  post = "/:sections/:title/"
